interval: "0 */1 * * *"
webhook: "https://example.com/api/webhooks/123abc"
event: 123456
event_title: "Example event!"
event_url: "https://example.com/"
event_image_url: "https://example.com/image.png"